### ISSUE TITLE
Feature request: ignore holidays

### ISSUE THREAD

**Issue by jhqv** [partofthething/next-holiday-sensor#1]
Thanks for creating this useful sensor!

In Sweden, every Sunday is considered as a holiday. This means that this sensor always returns 0-6 in "days until next holiday", and that the list of holidays is very long.

I am aware that I can explicitly list the holidays I want in my sensor, but I'd rather exclude the ones I don't want - such as the Sundays, in this case. Would you consider that?

![image](https://user-images.githubusercontent.com/8491785/144853733-919d1bbd-95ea-477f-803d-187cb4067d0e.png)

Edit: I just saw [some related discussion](https://github.com/dr-prodigy/python-holidays/issues/472#issuecomment-922371451) that referred to "include sundays" which can be passed when initializing the library. If it was possible to pass this parameter to the Holidays library it would solve my issue.

**Comment by partofthething** [comment]
Ah nice! Yes I'd be happy to accommodate this. I'll try to start with just allowing you to pass that parameter.

**Comment by partofthething** [comment]
Ok I added the ability to pass the kwargs _and_ the ability to ignore certain holidays in the latest release. Updated config and examples in the readme 🍸
