### ISSUE TITLE
Switch display language

### ISSUE THREAD

**Issue by e0909** [partofthething/next-holiday-sensor#6]
The display language of the holidays is English -  Im not 100% sure but it was in German some month before.  
Is there a way to change it? Based on the documentation of [phyton-holidays](https://github.com/vacanza/python-holidays) it seems to be possible to change that.

My Configuration:
- platform: next_holiday
  min_future_holidays: 12
  custom_holidays:
      "10-31": "Halloween"
  sources: 
    - country: "DE"
      state: "NW"

supported languages for DE/NW
![image](https://github.com/partofthething/next-holiday-sensor/assets/93178538/ff3aaf09-567e-43b0-882f-5214fd4cddf3)
![image](https://github.com/partofthething/next-holiday-sensor/assets/93178538/01083a0a-f79f-4964-a957-c45196b67cf6)

**Comment by kebabuschi** [comment]
Same for me. Would be nice if it could be fixed.

**Comment by partofthething** [comment]
Sure, I should be able to pass a config variable like that over to the backing library. I haven't changed anything here but maybe the dependency updated defaults or something. Will check into it!

**Comment by partofthething** [comment]
Oh, wait a minute, I think this already may be supported. We have a special kwargs configuration entry that works as a passthrough to the underlying holiday library. Can you try config like:

```
platform: next_holiday
min_future_holidays: 12
custom_holidays:
    "10-31": "Halloween"
sources:
   - country: "DE"
     state: "NW"
     kwargs:
       language: de
```
?

I added that kwargs passthrough to support any other future [config options that python-holidays supports. ](https://python-holidays.readthedocs.io/en/latest/api.html#holidays.holiday_base.HolidayBase)

**Comment by e0909** [comment]
Works for me! Thanks a lot.
![image](https://github.com/partofthething/next-holiday-sensor/assets/93178538/31e8525c-a60f-434a-b853-dd461b87e1b0)
